#!/bin/sh
set -e

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if command -v update-icon-caches >/dev/null; then
		update-icon-caches /usr/share/icons/Fluent /usr/share/icons/Fluent-dark /usr/share/icons/Fluent-light
	fi
fi
